### ISSUE TITLE
Add Bengali Wikisource

### ISSUE THREAD

**Issue by bodhisattwawiki** [wikisource/ws-search#1]
Hi Sam, can you add Bengali Wikisource for this tool. Thanks.

**Comment by samwilson** [comment]
Will do! :-) Well, sort of have already...

So, the idea is that this will go through all Wikisources (currently 64) and scrape each of them for all metadata. So far, a good idea, except for the fact that it's hanging on something in a French page and karking it at that point (and so never getting to the next Wikisource). Oh, and it's not doing it in alphabetical order or anything sensible....

:-) So, stay tuned, will have something to report before long I hope!

**Comment by samwilson** [comment]
Okay, the data will be rebuilt periodically, but `bn` is now being processed. e.g. the complete list of all works: https://tools.wmflabs.org/ws-search/?title=%25&author=&lang=bn&output_format=table&has_index=na (might be a bit slow to load).

**Comment by BodhisattwaMandal** [comment]
Reopening
