### ISSUE TITLE
Add Bengali Wikisource

### ISSUE THREAD

**Issue by bodhisattwawiki** [wikisource/ws-search#3]
Hi Sam, can you please add Bengali Wikisource for this tool. Its still missing. See [this issue](https://github.com/wikisource/ws-search/issues/1). Thanks.

**Comment by samwilson** [comment]
Sorry! There really are problems with the stability of the scraping by this tool. :-( I keep trying to make it work better, but things keep falling over. I'm trying to make it better. :-)

Anyway, I've kicked off another scrape of bn.wikisource and so the works should start populating now. The recent changes is also scraped every three hours.
